[package]
name = "egomoose/character-sounds"
version = "0.1.0"
license = "MIT"
description = "https://github.com/EgoMoose/character-sounds"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]