[package]
name = "egomoose/character-sounds"
version = "0.2.1"
license = "MIT"
description = "https://github.com/EgoMoose/character-sounds"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Signal = "stravant/goodsignal@0.2.1"